### ISSUE TITLE
update Noesis website link

### ISSUE THREAD

**Issue by poVoq** [viciious/noesis_iqe#3]
New download location of Noesis:
http://www.richwhitehouse.com/index.php?content=inc_projects.php#prjmp91

**Comment by viciious** [comment]
Update it where?

**Comment by adem4ik** [comment]
I guess he means https://github.com/viciious/noesis_iqe/blob/master/README.md

**Comment by poVoq** [comment]
yes :)

**Comment by viciious** [comment]
Fixed long time ago
